# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Riding',
            fields=[
                ('riding_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('result_lib', models.FloatField()),
                ('percent_lib', models.FloatField()),
                ('swing_lib', models.FloatField()),
                ('result_pc', models.FloatField()),
                ('percent_pc', models.FloatField()),
                ('swing_pc', models.FloatField()),
                ('result_ndp', models.FloatField()),
                ('percent_ndp', models.FloatField()),
                ('swing_ndp', models.FloatField()),
                ('result_oth', models.FloatField()),
                ('percent_oth', models.FloatField()),
                ('swing_oth', models.FloatField()),
            ],
        ),
    ]
