# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(choices=[('LIB', 'Liberal'), ('PC', 'Conservative'), ('NDP', 'NDP'), ('OTHER', 'OTH')], max_length=3)),
                ('vote_count', models.DecimalField(decimal_places=3, max_digits=10)),
                ('percent', models.DecimalField(decimal_places=3, max_digits=10)),
                ('swing', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='riding',
            name='percent_lib',
        ),
        migrations.RemoveField(
            model_name='riding',
            name='percent_ndp',
        ),
        migrations.RemoveField(
            model_name='riding',
            name='percent_oth',
        ),
        migrations.RemoveField(
            model_name='riding',
            name='percent_pc',
        ),
        migrations.RemoveField(
            model_name='riding',
            name='result_lib',
        ),
        migrations.RemoveField(
            model_name='riding',
            name='result_ndp',
        ),
        migrations.RemoveField(
            model_name='riding',
            name='result_oth',
        ),
        migrations.RemoveField(
            model_name='riding',
            name='result_pc',
        ),
        migrations.RemoveField(
            model_name='riding',
            name='swing_lib',
        ),
        migrations.RemoveField(
            model_name='riding',
            name='swing_ndp',
        ),
        migrations.RemoveField(
            model_name='riding',
            name='swing_oth',
        ),
        migrations.RemoveField(
            model_name='riding',
            name='swing_pc',
        ),
        migrations.AddField(
            model_name='riding',
            name='results',
            field=models.ManyToManyField(to='app.PartyResult'),
        ),
    ]
