# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 15:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180422_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='riding',
            name='percents',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='riding',
            name='swings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
        migrations.RemoveField(
            model_name='riding',
            name='results',
        ),
        migrations.AddField(
            model_name='riding',
            name='results',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
        migrations.DeleteModel(
            name='PartyResult',
        ),
    ]
