# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 02:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180516_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PollAveragePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django.contrib.postgres.fields.jsonb.JSONField(default=None)),
                ('date', models.DateField()),
            ],
        ),
    ]
