# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_poll_pollaveragepoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollaveragepoint',
            old_name='status',
            new_name='current',
        ),
        migrations.AddField(
            model_name='poll',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
