# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-19 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180517_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='pollaveragepoint',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='poll',
            name='pollster',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
